# permissions for end users to edit poddisruptionbudgetupdaters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: poddisruptionbudgetupdater-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pod-disruption-budget-updater
    app.kubernetes.io/part-of: pod-disruption-budget-updater
    app.kubernetes.io/managed-by: kustomize
  name: poddisruptionbudgetupdater-editor-role
rules:
- apiGroups:
  - poddisruptionbudgetupdater.k8s.faith
  resources:
  - poddisruptionbudgetupdaters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - poddisruptionbudgetupdater.k8s.faith
  resources:
  - poddisruptionbudgetupdaters/status
  verbs:
  - get
